/**
* NewsApp API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.0.0
* Contact: martinkovics.krisztian@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.example.newsapp.models

/**
 * 
 * @param status 
 * @param totalResult 
 * @param articles 
 */
data class NewsApiResponse (
    val status: kotlin.String? = null,
    val totalResult: kotlin.Int? = null,
    val articles: List<News>
) {

}

