/**
* NewsApp API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: 1.0.0
* Contact: martinkovics.krisztian@gmail.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.example.newsapp.models

import androidx.room.ColumnInfo


/**
 * 
 * @param id 
 * @param name 
 */
data class Source (
    @ColumnInfo(name = "id")
    val id: kotlin.String? = null,
    @ColumnInfo(name = "name")
    val name: kotlin.String? = null
) {

}

